apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeClaim: Recycle
  storageClassName: nfs
  nfs:
    server: 172.16.16.102
    path: "/srv/nfs/kubedata/pv1"
